services:

  db:
    image: mysql:8
    container_name: pg-mysql
    restart: always
    environment:
      MYSQL_DATABASE: pg_management
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./pg-management-backend
    container_name: pg-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pg_management
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build: ./pg-management-frontend
    container_name: pg-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data: