sonar.projectKey=pg-management-backend
sonar.projectName=PG Management Backend
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.java.source=21
sonar.exclusions=**/target/**,**/*.sql,**/Dockerfile
sonar.sourceEncoding=UTF-8
